### ISSUE TITLE
一些细节

### ISSUE THREAD

**Issue by kokororin** [DT27/EditorMD#1]
大部分主题都会载入jQuery，建议前台使用typeof判断一下，如果没有jQuery再载入插件的jQuery会不会更好？
另外强迫症忍不了这样的代码：(希望后台没有选择时，不要输出空的`$(function(){}` )
```html
        <script type="text/javascript">
$(function() {
    });
</script>
```

**Comment by DT27** [comment]
感谢建议！

jQuery的问题我试过，加了判断手动载入jQuery，文件总是在页面加载完才载入。
要让后面代码在jQuery加载完再执行的话，又需要其他插件来控制。以后我加上吧。

空代码我会处理的。

**Comment by kokororin** [comment]
https://github.com/DT27/EditorMD/blob/master/Plugin.php#L148
改为
```javascript
if (typeof jQuery === 'undefined')
    document.write("<script src=\"<?php echo $pluginUrl; ?>/lib/jquery.min.js\"></script>");
```
这样应该没有问题，我之前的插件也是这么处理的:satisfied:

**Comment by DT27** [comment]
我说怎么之前试一直加载不进来。。。原来是冒号跟斜杠的问题。。。
用这个解决了

    window.jQuery || document.write(unescape('%3Cscript%20type%3D%22text/javascript%22%20src%3D%22<?php echo $pluginUrl; ?>/lib/jquery.min.js%22%3E%3C/script%3E'));

马上提交更新

**Comment by DT27** [comment]
已经提交了，你试下怎么样。

**Comment by kokororin** [comment]
OK了，感谢！
