### ISSUE TITLE
编辑器里表格和主页显示不同

### ISSUE THREAD

**Issue by xuxiaodong326** [DT27/EditorMD#11]
编辑器里如下
![1](https://cloud.githubusercontent.com/assets/12394739/25261441/795c4a9c-2684-11e7-84a6-5fb2f9d60666.jpg)

主页里
![2](https://cloud.githubusercontent.com/assets/12394739/25261446/7e708aac-2684-11e7-8485-9b78b92ce274.JPG)

**Comment by DT27** [comment]
表格样式取决于主题。编辑器不影响前台展示效果。

2017-04-21 11:20 GMT+08:00 Xiaodong Xu <notifications@github.com>:
