### ISSUE TITLE
编辑器无法粘贴剪贴板内容？版本1.21

### ISSUE THREAD

**Issue by CHN-STUDENT** [DT27/EditorMD#12]
使用编辑器时候剪贴板内容无法粘贴上去。
但是用官方的可以粘贴。
而且去除文字的格式后就可以粘贴（例如使用记事本粘贴进去再复制出来）却可以。
能帮我解决问题吗？

请帮助我，谢谢。

**Comment by DT27** [comment]
我试过复制粘贴没问题，你是从哪里复制的什么内容？

**Comment by CHN-STUDENT** [comment]
@DT27 我从CHROME上复制网页上的一些文字无法粘贴，只能通过记事本消除格式后才能粘贴。

**Comment by DT27** [comment]
刚更新了，修复了Chrome中的粘贴问题。不影响其它浏览器。
