### ISSUE TITLE
粘贴上传问题

### ISSUE THREAD

**Issue by mmmwhy** [DT27/EditorMD#13]
之前用本Editor的时候，支持粘贴上传。
这是最喜欢typecho的地方了，因为他有一个这么棒的编辑器。

但是重装本编辑器发现不可以粘贴上传了，请问是什么情况呢？

typecho 1.0正式版
浏览器： chrome

**Comment by DT27** [comment]
等我明天测试哈

2017年5月24日 下午2:33，"Wing lee" <notifications@github.com>写道：

**Comment by DT27** [comment]
已修复，直接替换Plugin.php文件即可。
