### ISSUE TITLE
无法正常显示编辑器 一片空白

### ISSUE THREAD

**Issue by nishuo** [DT27/EditorMD#15]
![Image of Yaktocat](http://ww4.sinaimg.cn/large/0060lm7Tgy1fin5szz5phj30pb0himwz.jpg)

无法显示编辑器。
![Image of Yaktocat](http://ww4.sinaimg.cn/large/0060lm7Tgy1fin5sz2f2dj313w06mmx4.jpg)

**Comment by DT27** [comment]
看着像是editormd.js没加载完，你打开看看文件内容完整不。
这是源文件：https://github.com/DT27/EditorMD/blob/master/js/editormd.js

**Comment by TheFeiyang** [comment]
同无法加载
![default](https://user-images.githubusercontent.com/21673301/29530761-e9e663de-86d7-11e7-9f92-dcedcb7ad7ee.PNG)

**Comment by TheFeiyang** [comment]
CDN的缓存酿的祸系列
