### ISSUE TITLE
邮件链接解析有问题

### ISSUE THREAD

**Issue by xt-input** [DT27/EditorMD#16]
[input@xt-hacker.com](mailto:input@xt-hacker.com) 解析结果是：@xt-hacker.com"">input@xt-hacker.com

**Comment by DT27** [comment]
解决方法，禁用邮箱链接自动解析：EditorMD/js/editormd.js中151行，emailLink引号后面改为false。

MarkDown默认邮箱写法是`<mailto:dt27@dt27.org>`，这种写法会自动转为邮箱超链接，链接文本就是邮箱。
如果想自定义连接文本，写法： `[给我发邮件](mailto:dt27@dt27.org)`，这时需要禁用邮箱链接自动解析。

**Comment by xt-input** [comment]
谢谢！
