### ISSUE TITLE
启用MD解析按钮失效

### ISSUE THREAD

**Issue by TheFeiyang** [DT27/EditorMD#17]
在后台编辑文章处点击启用MD后,前台仍旧未解析,第二次进入编辑页仍旧禁用
![1](https://user-images.githubusercontent.com/21673301/29571747-9e100342-878c-11e7-8f0c-554a358b06d0.PNG)
![2](https://user-images.githubusercontent.com/21673301/29571748-9e1ede08-878c-11e7-9b67-4e91aba197e4.PNG)

**Comment by DT27** [comment]
启用后保存了吗

**Comment by TheFeiyang** [comment]
问题已经解决了,是MyEditor留下的烂摊子:Typecho直接不支持md了
