### ISSUE TITLE
不能关闭预览和使用全屏很多按钮无效

### ISSUE THREAD

**Issue by aaaol** [DT27/EditorMD#20]

**Comment by DT27** [comment]
实操未发现任何问题啊

**Comment by icedwork** [comment]
前一阵子（更新1.1版本 17.10.30之后）确实存在许多问题，一开始是编辑器里面的全部按钮失效，后来过了几天同步滚动也失效了，失效时观察console只有加载时loading的小图标报错显示404.
现在重新启用插件发现又恢复正常了, 期间没有更新任何插件和主题. 抱歉无法帮你定位bug

**Comment by aaaol** [comment]
![GIF.gif](https://i.loli.net/2017/11/12/5a084e2ac8720.gif)
我重新启用照旧 chrome 62 版本的 火狐也不行 手机没问题

**Comment by aaaol** [comment]
图怎么没了
![GIF.gif](https://i.loli.net/2017/11/12/5a084e2ac8720.gif)
https://i.loli.net/2017/11/12/5a084e2ac8720.gif

**Comment by DT27** [comment]
@aaaol 看下浏览器控制台有没有什么错误

**Comment by aaaol** [comment]
看起来没什么问题
![1GIF.gif](https://i.loli.net/2017/11/12/5a084fcec73bd.gif)
https://i.loli.net/2017/11/12/5a084fcec73bd.gif

**Comment by DT27** [comment]
@aaaol 右边窗口切换到Console，然后刷新重试

**Comment by aaaol** [comment]
看到一个报错
![11-12_21-49-20.png](https://i.loli.net/2017/11/12/5a08517e62651.png)
![2GIF.gif](https://i.loli.net/2017/11/12/5a08518dcb109.gif)

**Comment by DT27** [comment]
@aaaol 把这错误解决了就好了。js有错误后面的js都不会继续执行了。显示代理连接失败？检查下auto-slug插件。

**Comment by aaaol** [comment]
不行 我停用了那个插件没反映 现在我去官方那也没法用
![GIF.gif](https://i.loli.net/2017/11/13/5a0935701e582.gif)
WIN10 17025 版本64位 Chrome  61 浏览器

**Comment by DT27** [comment]
@aaaol 给我开个临时帐号，我看看

**Comment by aaaol** [comment]
https://blog.acgnt.org
账号密码都是123456

**Comment by DT27** [comment]
![2017-11-14 15 22 44](https://user-images.githubusercontent.com/1001048/32767747-b9e08592-c94f-11e7-992e-6c09ef001d76.jpg)
是不是可以确认是你浏览器的问题了😄

**Comment by aaaol** [comment]
我可以确认 IE内核的浏览器都没有问题 谷歌官方最新版本的浏览器无法兼容！

**Comment by DT27** [comment]
@aaaol 你清空下缓存看看吧，我的Chrome 62
