### ISSUE TITLE
希望编辑器的图片不要自动加a标签

### ISSUE THREAD

**Issue by CHN-STUDENT** [DT27/EditorMD#23]
今天这个编译器发现图片的会自动加上`<a></a>`标签，图片可以在文章打开，但是原生编辑器不会，我想知道怎么把这个去掉，像原生编译器那样。

**Comment by DT27** [comment]
编辑器并不会自动给图片加上链接，你是在编辑器里发现的，还是文章发布后发现的。文章发布后再编辑，编辑器里的图片有链接吗？方便的话发下文章地址我看下。

**Comment by CHN-STUDENT** [comment]
@DT27 
![tim 20171122184750](https://user-images.githubusercontent.com/21209416/33123649-ad991274-cfb5-11e7-9c4d-441a0422390f.jpg)
哦抱歉我的锅，刚试了，这个图片地址写了图片就会显示。
而写图片链接就会给图片添加上`<a>`标签能被打开。
抱歉打扰您了，谢谢您写出的typecho插件。
