### ISSUE TITLE
LNMP搭建的网站，阿里云下绑定了两个域名解析到网站，一个域名下编辑器按钮正常，另一个域名下编辑器按钮出现异常如图

### ISSUE THREAD

**Issue by traceless0929** [DT27/EditorMD#26]
![tim 20180306125434](https://user-images.githubusercontent.com/12078678/37014736-9837afce-213d-11e8-9ddf-02718235cf08.png)

**Comment by DT27** [comment]
看浏览器控制台有没有文件加载失败~

**Comment by traceless0929** [comment]
解决了，问题出在typecho_options表中siteUrl
