### ISSUE TITLE
编辑器布局问题

### ISSUE THREAD

**Issue by duoduoeeee** [DT27/EditorMD#27]
在非全屏模式下，编辑器会这样显示：

![image](https://user-images.githubusercontent.com/14347369/37200732-a6ec8ad2-23c0-11e8-9bfa-2caeceb61f7b.png)

在全屏模式下，编辑器则会这样显示：

![image](https://user-images.githubusercontent.com/14347369/37200759-bd345504-23c0-11e8-95d9-168c89925393.png)

难以使用。

屏幕是缩放1.25倍的1920x1080高分屏，Firefox Quantom 58，Fedora 64位。

**Comment by DT27** [comment]
看看控制台有没有什么错误吧。

**Comment by duoduoeeee** [comment]
浏览器console没有输出……

**Comment by DT27** [comment]
下了fedora live盘虚拟机启动黑屏。。。
下了server dvd虚拟机安装完，正在装桌面环境。。。

**Comment by duoduoeeee** [comment]
卧槽 赞美大佬

**Comment by DT27** [comment]
我不行了，，，fedora装不上桌面。。。
你给我开个测试账号我去你网站看看吧，或者你用别的平台浏览器试试。

**Comment by duoduoeeee** [comment]
https://lingduo.net.cn/dashboard-mng

用户 yousa
密码 yousa6666

赞美大佬

**Comment by DT27** [comment]
找到问题了，cloudflare的锅，你看看能不能禁用后台的cloudflare缓存？

**Comment by duoduoeeee** [comment]
这样啊，我试试

**Comment by duoduoeeee** [comment]
我禁了 usr 目录的缓存，但是还是这样

我开开发者模式看看

**Comment by duoduoeeee** [comment]
禁了全站缓存 好了

这是什么操作

**Comment by DT27** [comment]
问题应该是出在cloudflare的js文件合并压缩上，你试试能不能设置只缓存，不合并优化代码。

**Comment by duoduoeeee** [comment]
js压缩……我试试

**Comment by duoduoeeee** [comment]
- 关闭了 usr 目录的无缓存 页面规则
- 关闭了 speed 中 js 自动压缩的开关
- 关闭了开发模式

问题复现

**Comment by duoduoeeee** [comment]
- 关闭了Accelerated Mobile Links设置
- 关闭了Rocket Loader

问题解决

**Comment by DT27** [comment]
😂 cloudflare套路太多~

**Comment by duoduoeeee** [comment]
_(:з」∠)_

**Comment by duoduoeeee** [comment]
再次感谢并赞美大佬！
