### ISSUE TITLE
已拦截跨源请求：同源策略禁止读取位于

### ISSUE THREAD

**Issue by majie88881234** [DT27/EditorMD#29]

**Comment by majie88881234** [comment]
fontawesome-webfont.woff2?v=4.3.0 的远程资源。（原因：CORS 头缺少 'Access-Control-Allow-Origin'）。  （未知）

**Comment by blinkdr** [comment]
访问的域名跟你在后台“设置->基本设置->站点地址”要一致，比如设置www.xxx.com，访问也应该是这个地址，xxx.com好像就报错

**Comment by DT27** [comment]
https网站，站内资源尽量放到同一个域名下。
