### ISSUE TITLE
无法开启插件

### ISSUE THREAD

**Issue by ghost** [DT27/EditorMD#3]
报错信息: Server Error
环境: Nginx 1.9.12 (Windows Version), PHP7.0.4

**Comment by DT27** [comment]
@v-sky 没有详细错误信息我也没办法~

**Comment by v-sky** [comment]
开启时候直接报错,提示Server Error, 别的啥也没有......
顺带提一下, 用的是最新的开发版

**Comment by DT27** [comment]
@v-sky 等我搭个环境试一下。

**Comment by NIGHT-CORE** [comment]
今天也是这个问题，怎么开启错误报告

**Comment by DT27** [comment]
@NIGHT-CORE config.inc.php 添加`define('__TYPECHO_DEBUG__', true);`试试。

**Comment by fiht** [comment]
同样无法开启，后端是Nginx+php5
界面显示 Server Error

**Comment by DT27** [comment]
@fiht 建Nginx环境好麻烦。。。等会儿吧，正在研究 Docker。。。

**Comment by LiYongS** [comment]
大多数启用插件出现 Server Error 是因为目录名称不对，哪怕只是后面多了一个空格
