### ISSUE TITLE
咨询一下代码高亮部分

### ISSUE THREAD

**Issue by feeeei** [DT27/EditorMD#31]
不管是在文章编辑页面还是在文章预览页面，都看不到代码块中高亮的效果

是因为组件默认不支持代码高亮吗？  
还是说是我需要在 Typecho 中配置代码高亮相关的配置？

组件别的方面都用起来感觉很方便，谢谢~~~

**Comment by DT27** [comment]
尽管你关了，我还是说一下~
内置的代码高亮我去掉了，为了减少体积，而且单独代码高亮插件比内置好用。
推荐用[Google Code Prettify](https://imnerd.org/google-code-prettify-plugin-for-typecho-0-9.html)插件。
