### ISSUE TITLE
启用接管前台markdown解析器后文章摘要出现异常

### ISSUE THREAD

**Issue by EzrealCdev** [DT27/EditorMD#32]
文章摘要会显示markdown代码，参考网站 www.ezrealc.tech

**Comment by tuojia** [comment]
[附件图片](https://share.weiyun.com/5ZCdl4e)
我用的是“Single”主题，使用本插件，开启“接管前台 Markdown 解析”后，右侧的目录树就不再显示了。
我查看主题的 Js 文件，发现是查找 “.post-content” 下面 id 为 “title-数字" 的 h2-h6 标签的。原主题直接调用框架的 id 是没有问题的。
而开启接管后，这些标题的 id 全变了，导致主题找不到对应的 id 名，于是就不显示了……

我需要用到这个插件来编写及显示 LaTeX 公式，同时也想用 Single 主题的目录树（毕竟比 TOC 的好看多了），所以想问问有没有办法修改一下，使得这个插件独立不改变 h2-h6 这些的 id 名。如果有，麻烦告知一下，也不必修改到这个项目来。谢谢了～～

**Comment by DT27** [comment]
@tuojia 试试把主题js文件放到最后加载。
Markdown是在js里解析的，主题js执行时文章内容还没生成。

**Comment by YIOIY** [comment]
> 文章摘要会显示markdown代码，参考网站 [www.ezrealc.tech](http://www.ezrealc.tech)

这个链接打不开

**Comment by EzrealCdev** [comment]
不好意思，这都过了一年多了，后面实在没法多方面考虑后换了其他系统，现在网站是下线等待完善的状态。忘了close了

**Comment by DT27** [comment]
文章摘要改为系统自带解析了。
