### ISSUE TITLE
关于Aria主题的兼容问题

### ISSUE THREAD

**Issue by White-Clouds** [DT27/EditorMD#34]
用这个编辑器与[Aria](https://eriri.ink/archives/Typecho-Theme-Aria.html)共用时会存在要刷新才会显示文章的问题

**Comment by i-cooltea** [comment]
是因为主题使用了页面无刷新技术 Pjax 
而插件只在加载PHP代码的时候才会去渲染 markdown 
解决方案是 在调用完pjax之后 再渲染一次markdown

**Comment by DT27** [comment]
#36
