### ISSUE TITLE
七牛的资源全都炸了

### ISSUE THREAD

**Issue by liesauer** [DT27/EditorMD#47]
![image](https://github.com/DT27/EditorMD/assets/8676741/14782618-7e0a-4944-8037-2563528df16d)

**Comment by liesauer** [comment]
请问哪里可以搞到这一整套完整的资源，想放在自己的七牛下面

**Comment by DT27** [comment]
[归档.zip](https://github.com/DT27/EditorMD/files/13647107/default.zip)
所有表情图片。
/usr/plugins/EditorMD/js/editormd.min.js //cdn.staticfile.org/emoji-cheat-sheet/1.0.0
/usr/plugins/EditorMD/Plugin.php 369行 //cdn.staticfile.org/emoji-cheat-sheet/1.0.0
这两个地方改成你的表情图片路径就行了。

**Comment by liesauer** [comment]
好的，感谢！
