### ISSUE TITLE
关于前端呈现。

### ISSUE THREAD

**Issue by lzhd24** [DT27/EditorMD#6]
1. 代码块多语言风格，编辑器有效果，前端没有效果。
2.那个image加载中的gif，每篇文章都有，很难看，我直接删掉了。

总体很好，辛苦，多谢。

**Comment by neoFelhz** [comment]
前端需要代码高亮模块配合才能显示。编辑器应该没有接管这一块。

**Comment by neoFelhz** [comment]
对于那个GIF，如果不用emoji和科学公式，把插件设置里两个开关关掉就行，加载会快很多。
