### ISSUE TITLE
接管后的Markdown解析对Aplayer的兼容

### ISSUE THREAD

**Issue by neoFelhz** [DT27/EditorMD#7]
我启用了[Aplayer](https://github.com/zgq354/APlayer-Typecho-Plugin)的播放器插件，同时启用了Editor.MD的前台Markdown解析，结果Aplayer插件没法正常显示了。

**Comment by neoFelhz** [comment]
我想要实现文章和Aplayer插件共存。

**Comment by DT27** [comment]
@neoFelhz  您好，为了兼容 APlayer 编辑器中增加了 Markdown开关 功能，文章内有 APlayer 时只能禁用该文章的 Markdown ~ 这个暂时没有其它解决办法。Sorry~

**Comment by neoFelhz** [comment]
好吧，那我另外去找找有没有能支持的markdown解析库吧。。。
辛苦了~

**Comment by DT27** [comment]
@neoFelhz  Typecho 自带的就很好啊。
