### ISSUE TITLE
怎么插入空行

### ISSUE THREAD

**Issue by khs1994** [DT27/EditorMD#9]
只能通过添加`<br />`来解决吗？

**Comment by DT27** [comment]
直接回车就是个空行啊。。。
![2016-11-12 08 40 57](https://cloud.githubusercontent.com/assets/1001048/20234267/c8506cfe-a8b3-11e6-8f6d-afb9a79a4b40.jpg)

**Comment by khs1994** [comment]
是我主题的问题吧，默认的主题没问题。

**Comment by khs1994** [comment]
- [ ]
